services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name="portainer"
      - tsdproxy.container_port=9000
      - tsdproxy.tlsvalidate="false"

volumes:
  portainer_data: