services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/tsdproxy:/data
      - /opt/docker/.config/tsdproxy:/config
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  datadir: